### ISSUE TITLE
External Links Open in New Window 1.0.1 | Not work on new Forum

### ISSUE THREAD

**Issue by PeopleInside** [RMcGirr83/phpBB-3.1-elonw#6]
Hi,
I have activated your extension version 1.0.1 for phpbb 3.1 all work fine.
Also in the red notice like here: https://forum.peopleinside.it/viewforum.php?f=2 but on new topic I create link are not open in new window: 
https://forum.peopleinside.it/viewforum.php?f=9

**Comment by RMcGirr83** [comment]
It is working fine on your forum.  You need to provide more information than you have.  Not sure why you think it isn't working.

**Comment by PeopleInside** [comment]
Simple, click that URL
https://forum.peopleinside.it/viewforum.php?f=9
and try yo open the link in the red notice. It will not open in new window

**Comment by RMcGirr83** [comment]
Of course it won't as it is part of the same domain.

**Comment by PeopleInside** [comment]
But here it works https://forum.peopleinside.it/viewforum.php?f=2

**Comment by PeopleInside** [comment]
Can be because i changed the domain from peopleinside.it/forum/ to forum.peopleinside.it?

**Comment by RMcGirr83** [comment]
It is opening in a new window because that is how you have coded it for that forum description.  Here is the code that you have where it doesn't open `<a class="postlink" href="http://www.peopleinside.it">http://www.peopleinside.it</a>` and here is the code where it does `<a onclick="window.open(this.href);return false;" href="http://www.peopleinside.it" class="postlink">http://www.peopleinside.it</a>` you have placed the window.open in the forum description.

**Comment by PeopleInside** [comment]
I have no place nothing... however the footer works fine. So maybe if I want set the links on top also opening in a new window where I have to set? There is an option or I need code? Thanks anyway.

**Comment by RMcGirr83** [comment]
`I have no place nothing` that isn't possible as the extension adds an "Opens in new window" title to the link just as it does for all the links in your footer.
